# Generated by Django 3.1.5 on 2021-01-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
                ('thumbnail_url', models.URLField(max_length=100)),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
